import Head from "next/head";

import Navbar from "../components/Navbar";
import Header from "../components/Header";
import PageNav from "../components/PageNav";
import Navigation from "../components/Navigation";
import CourseOverview from "../components/CourseOverview";
import UpcomingEvents from "../components/UpcomingEvents";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <PageNav />
      <div className="grid md:grid-flow-col px-5 md:px-10 py-2 gap-4 ">
        <Navigation />
        <CourseOverview />
        <UpcomingEvents />
      </div>
    </div>
  );
}
