import Head from "next/head";

import Navbar from "../components/Navbar";
import Header from "../components/Header";
import PageNav from "../components/PageNav";
import Navigation from "../components/Navigation";
import CourseOverview from "../components/CourseOverview";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <PageNav />
      <Navigation />
      <CourseOverview />
    </div>
  );
}
