import Head from "next/head";
import Image from "next/image";

import Navbar from "../components/Navbar";
import Header from "../components/Header";
import PageNav from "../components/PageNav";
import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <PageNav />
      <Navigation />
      <div className="p-20">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam eaque
          inventore neque vero quis omnis vitae quisquam voluptates. Esse
          debitis non delectus ea praesentium eos voluptas natus cum, nulla
          deserunt.
        </p>
      </div>
    </div>
  );
}
